[package]
name = "rs-view-tracker"
version = "0.1.0"
authors = ["Pavel Senchanka <pavel.senchanka@gmail.com>"]

[dependencies]
chrono = "0.4"
chrono-tz = "0.4"
futures = "0.1.14"
hyper = "0.11.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
